#!/usr/bin/env bash
# shellcheck disable=SC1090,SC2155,SC2034

set_prompt() {
    # Reset
    Reset='\[\e[0m\]'

    # Bold
    Bold='\[\e[0;1m\]'

    # Underline
    Underline='\[\e[0;4m\]'

    # Bold underline
    BoldUnderline='\[\e[0;1;4m\]'

    # Regular foreground
    Black='\[\e[30m\]'
    Red='\[\e[31m\]'
    Green='\[\e[32m\]'
    Yellow='\[\e[33m\]'
    Blue='\[\e[34m\]'
    Purple='\[\e[35m\]'
    Cyan='\[\e[36m\]'
    White='\[\e[37m\]'

    # High Intensity foreground
    IBlack='\[\e[90m\]'
    IRed='\[\e[91m\]'
    IGreen='\[\e[92m\]'
    IYellow='\[\e[93m\]'
    IBlue='\[\e[94m\]'
    IPurple='\[\e[95m\]'
    ICyan='\[\e[96m\]'
    IWhite='\[\e[97m\]'

    # Regular background
    OnBlack='\[\e[40m\]'
    OnRed='\[\e[41m\]'
    OnGreen='\[\e[42m\]'
    OnYellow='\[\e[43m\]'
    OnBlue='\[\e[44m\]'
    OnPurple='\[\e[45m\]'
    OnCyan='\[\e[46m\]'
    OnWhite='\[\e[47m\]'

    # High Intensity background
    OnIBlack='\[\e[100m\]'
    OnIRed='\[\e[101m\]'
    OnIGreen='\[\e[102m\]'
    OnIYellow='\[\e[103m\]'
    OnIBlue='\[\e[104m\]'
    OnIPurple='\[\e[105m\]'
    OnICyan='\[\e[106m\]'
    OnIWhite='\[\e[107m\]'

    # get active conda environment
    if [[ -n ${CONDA_DEFAULT_ENV} ]]; then
        conda_env="(${IBlue}${CONDA_DEFAULT_ENV}${Reset}) "
    fi

    # check if current dir belongs to overlayed ROS package
    if [[ -n "${ROS_DISTRO}" ]] && [[ -n "$(which rospack)" ]]; then
        for package_path in $(rospack list | awk '{print $2}'); do
            if [[ "${PWD}" == "${package_path}"* ]]; then
                ros_package="${Green}✔︎${Reset}"
                break
            fi
        done
    fi

    # set the prompt
    if [[ "${SESSION_TYPE}" == "remote_ssh" ]]; then
        echo " ${conda_env}${IBlack}\h::\W${Reset}${ros_package}"
    else
        echo " ${conda_env}${IBlack}\W${Reset}${ros_package}"
    fi
}

# git prompt command
if [[ -f "${HOMEBREW_PREFIX}/etc/bash_completion.d/git-prompt.sh" ]]; then
    source "${HOMEBREW_PREFIX}/etc/bash_completion.d/git-prompt.sh"
fi

# git prompt options
export GIT_PS1_SHOWCOLORHINTS=true
export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_DESCRIBE_STYLE="contains"
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWUPSTREAM="auto"

#export PS1="$(set_prompt)"
export PROMPT_COMMAND+='__git_ps1 "$(set_prompt)" " "; '
