#!/usr/bin/env bash

#
# ~/.conda_init
#

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/george/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/george/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/george/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/george/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

export MAMBA_NO_BANNER=1
