"
" ~/.vim/vimrc
"

set nocompatible  " be IMproved, required
filetype off  " required
runtime vimrc.d/plugins.vim
filetype plugin indent on

runtime $VIMRUNTIME/defaults.vim

" saving
set updatetime=400  " autoupdate delay
set undofile  " maintain undo file
set undodir=$HOME/.vim/undo/  " undo file location
set noswapfile  " don't write swap file
set nowritebackup  " no backup before overwriting
set nobackup  " no persistent backups
set autoread  " auto-read modified open files

" set encodings and line ending formats
set fileencodings=ucs-bom,utf-8,cp1253,default,latin1  " tried on open
set encoding=utf-8  " encoding used for displaying inside vim
set fileformats=unix,mac,dos  " format order to be tried on a new buffer
set nrformats=bin,hex  " number formats to be checked for

" appearance
colorscheme sunyata
set concealcursor=c  " only conceal command mode
set conceallevel=1  " only conceal using 1 character
"set number  " show line numbers
set numberwidth=1  " smallest width at start
"set wrap  " wrap long lines
set sidescroll=1  " enable sidescrolling
set showmatch  " show matching parentheses
set noshowcmd  " hide typed command
let &fillchars = 'vert:│,diff:-,eob: ,lastline:.,fold: ,foldopen:▾,foldsep:│,foldclose:▸'
set showbreak=…  " show '…' at start of wrapped lines
set list  " show non-text characters
let &listchars = 'tab:|->,trail:·,conceal:◌,extends:…,precedes:…,nbsp:_'
set laststatus=2  " always show statusline

" behavior
set timeoutlen=1500  " leader timeout
set ttimeoutlen=50  " key sequence timeout
set maxmempattern=100000  " set maximum memory for pattern matching to 100Mb
"set regexpengine=1  " use old regex engine (WARNING: it's laggy)
set mouse=a  " enable mouse
let maxwinwidth=80  " minimum column width when formatting
set splitbelow  " open new horizontal windows at bottom
set splitright  " open new vertical windows at right
set previewheight=3  " set preview window height to 3
set autoindent  " autointent
set expandtab  " replace tabs with spaces
set tabstop=4      " ┐
set softtabstop=4  " ├ 4 spaces per Tab, fold every 4
set shiftwidth=4   " ┘
set nojoinspaces  " don't insert 2 spaces after '.', '?' or '!'
set nofixendofline  " preserve EOL and the end of file
set backspace=indent,eol,start  " allow backspace in insert mode
set scrolloff=3  " lines to scoll before the reaching last
set sidescrolloff=5  " columnts to sroll before reaching the last
set whichwrap+=h,l,<,>,[,]  " fix line movement on line borders
"set wrap lbr  " wrap lines by word
set formatoptions=1jnpr  " no automatic line breaking
set breakindent  " wrap preserving indentation
set display=lastline  " show last wrapped line in window
set smoothscroll  " scroll screen lines (when wrap is on)
set shell=$SHELL\ -l  " login shell for 'term'
set shellcmdflag=-c  " login shell for '!'
set nolangremap  " disable a legacy behavior that can break plugin maps
let &clipboard = has('unnamedplus') ? 'unnamed,unnamedplus' : 'unnamed'


" folding
set foldenable  " enable folding
set foldmethod=indent  " fold only based on intentation
set foldignore=  " don't ignore any lines
set foldlevel=2  " depth of first folding
set foldnestmax=99  " depth of last folding
set foldcolumn=0  " hide fold column

" searching
set smartcase  " case sensitive only if Uppercase
set hlsearch  " highlight search matches
set incsearch  " do incremental search

" autocompletion
set completeopt=menuone,noinsert,preview,popup  " select 1st item without inserting
set complete=t,.,i  " scan tags, curr. buffer, incl. files
set shortmess=mnrxcoTWF  " minimal message shortening & shut off completion messages
set belloff+=ctrlg  " silent completion
set wildmenu  " display completion matches in a status line

" custom fold text method
runtime vimrc.d/foldtext.vim

" custom status line (source before autocommands.vim)
runtime vimrc.d/statusline.vim

" autocommands
runtime vimrc.d/autocommands.vim

" mappings
runtime vimrc.d/mappings.vim
